### ISSUE TITLE
Dank and Exchanging Gadget Bug

### ISSUE THREAD

**Issue by moshner** [worldofpannotia/minecraft-modpack#100]
I don't know who to report this bug to. When I replace dirt with exchanging gadget from the dank the replaced blocks do not go back into the dank or my inventory. They are just deleted.

:(

v8.0.1

**Comment by chimericdream** [comment]
Looks like a known bug between the two. From the conversations, it sounds like the underlying issue is in Dank Storage. I'll turn on notifications for that ticket to keep an eye out for when it gets fixed.

[Building Gadgets ticket](https://github.com/Direwolf20-MC/BuildingGadgets/issues/615)
[Dank Storage ticket](https://github.com/Tfarcenim/Dank-Storage/issues/105)
